name: Delta-Incremental-Build-SFDX-Action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Auth-SFDX-authurl'
        run: |
              ls -la
              sfdx force:auth:sfdxurl:store -f ./authurl -s -a DEVHUB       
      - name: 'Run shell Generate diff'
        run: |
              dir
              chmod +x ./githubaction.sh
              echo start
              sed -i -e 's/\r$//'  githubaction.sh
              ./githubaction.sh           
        shell: bash
        
    
        
      

       
       
