name: awscli
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Installawscli'
        run: |
              curl -L -o install-aws.sh https://raw.githubusercontent.com/unfor19/install-aws-cli-action/master/entrypoint.sh && \
              chmod +x install-aws.sh
              ./install-aws.sh "v2" "amd64"
              rm install-aws.sh 
                    
      - name: 'Run shell Generate diff'
        run: |
              dir
              
