name: awscli
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Installawscli'
        run: |
             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
             unzip awscliv2.zip 
             sudo ./aws/install
             aws --version
                    
      - name: 'Run shell Generate diff'
        run: |
              dir
              
